// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Labels_KM49.Models;
using Microsoft.EntityFrameworkCore;

namespace Labels_KM49.Data;

public partial class PilotosContext : DbContext
{
    public PilotosContext()
    {
    }

    public PilotosContext(DbContextOptions<PilotosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DashDatum> DashData { get; set; }

    public virtual DbSet<EjE> EjEs { get; set; }

    public virtual DbSet<EjFa> EjFas { get; set; }

    public virtual DbSet<EjesinFa> EjesinFas { get; set; }

    public virtual DbSet<EjfasinG> EjfasinGs { get; set; }

    public virtual DbSet<Ejlist> Ejlists { get; set; }

    public virtual DbSet<EjlistG2> EjlistG2s { get; set; }

    public virtual DbSet<EsinFa> EsinFas { get; set; }

    public virtual DbSet<FasinG> FasinGs { get; set; }

    public virtual DbSet<Km49E> Km49Es { get; set; }

    public virtual DbSet<Km49Fa> Km49Fas { get; set; }

    public virtual DbSet<Km74> Km74s { get; set; }

    public virtual DbSet<PilotosList> PilotosLists { get; set; }

    public virtual DbSet<PilotosListKmg2> PilotosListKmg2s { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=10.100.87.20;Initial Catalog=Pilotos;Persist Security Info=True;User ID=apps;Password=Matsop914.;TrustServerCertificate=true;MultipleActiveResultSets=true");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<EjesinFa>(entity =>
        {
            entity.ToView("EJEsinFA");
        });

        modelBuilder.Entity<EjfasinG>(entity =>
        {
            entity.ToView("EJFAsinG");
        });

        modelBuilder.Entity<EsinFa>(entity =>
        {
            entity.ToView("EsinFA");
        });

        modelBuilder.Entity<FasinG>(entity =>
        {
            entity.ToView("FAsinG");
        });

        modelBuilder.Entity<PilotosListKmg2>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}