// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Labels_KM49.Models;

public partial class DashDatum
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("KMTotal")]
    public int? Kmtotal { get; set; }

    [Column("KMg")]
    public int? Kmg { get; set; }

    [Column("KMe")]
    public int? Kme { get; set; }

    [Column("KMfa")]
    public int? Kmfa { get; set; }

    [Column("EJTotal")]
    public int? Ejtotal { get; set; }

    [Column("EJg")]
    public int? Ejg { get; set; }

    [Column("EJe")]
    public int? Eje { get; set; }

    [Column("EJfa")]
    public int? Ejfa { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [Column("KMConstruidas")]
    public int? Kmconstruidas { get; set; }

    [Column("KMEmbarcadas")]
    public int? Kmembarcadas { get; set; }

    [Column("EJConstruidas")]
    public int? Ejconstruidas { get; set; }

    [Column("EJEmbarcadas")]
    public int? Ejembarcadas { get; set; }
}